// Além do Mar — all user-facing copy (pt-BR).
// Edit in the Tweaks panel (modo edição) or replace this file after exporting JSON.

window.AdM_CONTENT_DEFAULTS = {
  meta: {
    contactEmail: 'info@alemdomar.com',
    founderName: 'Luana',
    footerCopyright: '© 2026 Além do Mar · Carreira & recomeço no exterior',
  },
  landing: {
    nav: {
      ferramentas: 'Ferramentas',
      comoFunciona: 'O que muda',
      guia: 'Guia gratuito',
      sobre: 'Sobre',
      revisores: 'Revisores humanos (em breve)',
    },
    hero: {
      pill: 'Beta · feito por brasileiros, fora do Brasil',
      title1: 'Sua experiência de trabalho no Brasil,',
      title2a: 'traduzida para',
      title2em: 'contratação em',
      title2b: 'Dublin, Londres e Berlim.',
      sub: 'Currículo reescrito no formato que o recrutador europeu espera, com resultados quando você tem e clareza quando ainda não tem os números.',
      ctaPrimary: 'Traduzir minha experiência →',
      ctaReviewers: 'Revisores humanos (em breve)',
      ctaComo: 'Ver antes e depois',
      trust1: '✓ Sem login',
      trust2: '✓ Você escreve em português · saída em inglês',
      trust3: '✓ Sem exagero · sem inventar métrica',
      destinoLabel: 'Cidade de destino',
    },
    transform: {
      eyebrow: 'O que muda',
      title1: 'Mesma pessoa.',
      title2: 'Mesma experiência.',
      title3a: 'Outra leitura.',
      beforeLabel: 'Antes · como você escreveu',
      beforeText: 'Analista de atendimento ao cliente.\nResponsável por suporte ao cliente.\nUso de sistema interno.\nContato com equipe.',
      afterLabel: 'Depois · como o recrutador lê',
      afterTitle: 'Customer Support Specialist',
    },
    city: {
      eyebrow: 'Sabia disso?',
      titleA: 'Cada cidade,',
      titleEm: 'um currículo diferente.',
      body: 'O que funciona no Brasil pode ser descartado por um recrutador europeu em segundos. Dublin, Londres e Berlim têm regras distintas, e a ferramenta adapta ao seu destino.',
      cta: 'Adaptar ao estilo de {city} →',
      hint: '1 crédito grátis · cerca de 30 segundos',
    },
    quirks: {
      eyebrow: 'Por que funciona',
      title: 'Os 8 vícios mais comuns do currículo brasileiro.',
      items: [
        { n: '01', title: 'Descritivo, sem resultados numéricos', body: '"Responsável por atendimento" → quanto, com que frequência, o que melhorou.' },
        { n: '02', title: 'Títulos genéricos', body: 'Analista, Assistente e Coordenador não significam o mesmo lá fora. Aqui são mapeados para o equivalente real do mercado.' },
        { n: '03', title: 'Habilidades jogadas no texto', body: '"Proativo, dinâmico" sai. Só fica o que você consegue provar.' },
        { n: '04', title: 'Educação inflada', body: 'Em UK/Irlanda, experiência > diploma. Reordena.' },
        { n: '05', title: 'Parágrafos longos', body: 'Vira tópico escaneável. Uma ideia por linha.' },
        { n: '06', title: '"Sistemas internos"', body: 'Vira CRM, ERP, ou a ferramenta com nome.' },
        { n: '07', title: 'Subestimar o escopo', body: '"Auxiliei" vira "contributed to". Sem mentir.' },
        { n: '08', title: 'Tom informal demais', body: 'Estrutura limpa, neutra e profissional, pronta para leitura rápida.' },
      ],
    },
    toolkit: {
      eyebrow: 'A caixa de ferramentas',
      titleA: 'Tudo que você não sabia que precisava',
      titleEm: 'para essa transição.',
      body: 'Não é só currículo. É o pacote inteiro: filtro automático (ATS), diagnóstico de “por que não me responderam”, salário real no destino e roteiros para situações difíceis no trabalho.',
      quickAccess: 'Acesso rápido',
      quickCareer: '📄 Tradutor de Carreira',
      quickCultural: '🌍 Tradutor Cultural',
      quickHiring: '🔍 Por que sem resposta?',
    },
    cta: {
      title1: 'Pronto para ver sua experiência',
      titleEm: 'do outro lado do mar?',
      button: 'Começar (leva 30 segundos)',
    },
    cultural: {
      eyebrow: 'Também incluso',
      titleA: 'Tradução cultural: o que ninguém te conta sobre',
      titleEm: 'trabalhar fora',
      titleB: '.',
      body: 'Diferenças culturais reais no trabalho, roteiros para reuniões, erros comuns no primeiro ano fora e o que parece estranho, mas é normal. Direto, prático, sem clichê.',
      button: 'Abrir tradutor cultural',
    },
    guide: {
      pill: 'Guia gratuito',
      titleA: 'Carreira no exterior:',
      titleEm: 'o mapa antes da ferramenta',
      body: 'Um guia gratuito para brasileiros que estão planejando sair, chegando agora ou tentando se reposicionar fora do Brasil. CV, LinkedIn, entrevistas, networking, salário e mudança de país em uma sequência simples.',
      button: 'Quero receber o guia →',
      note: 'PDF em breve. Entre na lista e receba quando estiver disponível.',
    },
    reviewers: {
      pill: 'Olho humano · em breve',
      titleA: 'Quando a IA não é suficiente:',
      titleEm: 'revisores que conhecem o mercado',
      titleB: '.',
      body: 'Profissionais reais (recrutadores, headhunters e coaches de carreira) que já contrataram brasileiros no exterior. A IA orienta; eles validam. Contato direto, sem comissão.',
      button: 'Quero ser avisado(a) →',
    },
    footer: {
      contato: 'Contato',
      privacidade: 'Privacidade',
    },
    tools: {
      essentials: { title: 'Essencial', subtitle: 'O começo de tudo' },
      diagnosis: { title: 'Diagnóstico', subtitle: 'Entenda o que está acontecendo' },
      preparation: { title: 'Preparação', subtitle: 'Esteja pronto para os desafios' },
      cultural: { title: 'Cultura', subtitle: 'Adapte-se ao novo ambiente' },
      advanced: { title: 'Avançado', subtitle: 'Para situações específicas' },
      items: {
        career: { eyebrow: 'Currículo', title: 'Tradutor de carreira', body: 'Currículo, headline do LinkedIn, vocabulário do setor e tópicos para entrevista.' },
        ats_check: { eyebrow: 'Filtro ATS', title: 'Vai passar do filtro?', body: 'Cole a vaga e seus tópicos. Mostra o que falta para passar no filtro automático (ATS).' },
        salary_reality: { eyebrow: 'Negociação', title: 'O que você vale aqui', body: 'Faixa real, custo de vida no destino e valor de referência para ancorar a negociação.' },
        hiring_reality: { eyebrow: 'Diagnóstico', title: 'Por que sem resposta?', body: 'Visto, ATS, mismatch ou timing. A verdade desconfortável, com plano de ação.' },
        rejection_decoder: { eyebrow: 'Decoder', title: 'O que essa rejeição quer dizer', body: 'Decifra cada frase padrão. Foi você ou foi estrutural?' },
        interview_sim: { eyebrow: 'Entrevista', title: 'Treino de entrevista', body: 'Perguntas reais do seu mercado-alvo, com tom cultural e correção de erros.' },
        cultural: { eyebrow: 'Cultura', title: 'Tradutor cultural', body: 'Diferenças reais no trabalho, scripts, erros do primeiro ano.' },
        social_scripts: { eyebrow: 'Scripts', title: 'Como dizer isso', body: 'Discordar do chefe, recusar trabalho extra, sair pontualmente. As palavras certas.' },
        say_it_better: { eyebrow: 'Reescrita', title: 'Diga isso melhor', body: 'Você escreve do jeito que pensa. Recebe em inglês profissional, no tom certo.' },
        identity_reframe: { eyebrow: 'Identidade', title: 'Me sinto perdido', body: 'O que pouca gente nomeia: o reset de identidade profissional. Reformulado, com um próximo passo concreto.' },
      },
    },
  },
  sobre: {
    back: '← Voltar ao início',
    pill: 'Sobre',
    titleA: 'Feito por brasileiros,',
    titleEm: 'fora do Brasil.',
    intro: 'O Além do Mar traduz experiência de trabalho brasileira para o formato que o recrutador europeu espera. Sem curso, sem promessa vazia e sem inventar métrica.',
    whyTitle: 'Por que existe',
    whyP1: 'Muita gente com experiência real trava no currículo, no ATS, na entrevista e na cultura do escritório europeu, não por falta de competência, mas por diferença de formato e de leitura.',
    whyP2: 'Construímos ferramentas em português que reescrevem sua experiência com honestidade: resultados quando existem, limites quando não existem, e vocabulário que recrutadores em Dublin, Londres ou Berlim reconhecem.',
    dosTitle: 'O que fazemos (e o que não fazemos)',
    dosItems: [
      'Traduz carreira, cultura de trabalho, salário, ATS e diagnóstico de candidatura.',
      '1 crédito grátis para testar. Depois, você paga só o que usar, sem assinatura.',
      'Não vendemos visto, emprego garantido nem promessa de contratação.',
      'Não exageramos seu histórico. Se faltar número, a IA avisa.',
    ],
    founderTitle: 'Quem está por trás (sem foto, por enquanto)',
    founderP1: '{name} construiu o Além do Mar depois de ver o mesmo padrão repetir: brasileiros competentes descartados por currículo mal adaptado, não por falta de talento.',
    founderP2: 'Por enquanto o produto fala mais alto que o rosto. Sem foto de fundadora, sem exposição pessoal em grupo, sem transformar ajuda em espetáculo. Quando a ferramenta estiver sólida e os revisores humanos no ar, abriremos mais da história por trás do nome.',
    founderP3: 'Isso não é esconder. É proteger o foco no que importa: sua tradução sair certa, rápida e honesta.',
    contactTitle: 'Contato',
    contactBody: 'Dúvida, parceria ou feedback? Escreva para nós. Respondemos em português.',
  },
  paywall: {
    reasonOut: 'Você usou seu crédito grátis',
    reasonAdd: 'Adicione créditos',
    title: 'Continue traduzindo sua experiência.',
    sub: 'Cada tradução usa 1 crédito. Sem assinatura e sem renovação automática: compra única, créditos sem validade.',
    footer: 'Pagamento seguro via Stripe. Sem cadastro e sem cartão salvo. Os créditos ficam neste navegador (identificador anônimo). Se você limpar os dados do navegador, perde o saldo.',
    buyError: 'Não foi possível abrir o pagamento. Tente de novo em instantes.',
  },
  privacy: {
    title: 'Privacidade & dados',
    p1: 'Um identificador anônimo neste navegador e seu saldo de créditos. O saldo também fica no nosso servidor (Cloudflare), ligado só a esse identificador, sem nome nem e-mail.',
    p2: 'Seu currículo e o texto que você cola. Depois que a tradução volta, você baixa e pronto. Não salvamos histórico no navegador nem no servidor.',
    p3: 'Quando você clica em traduzir, o texto digitado vai para a OpenAI gerar a resposta. Isso dura só o tempo do processamento. Não ficamos com cópia disso.',
    p4: 'Compra de créditos é feita no Stripe. Eles processam o pagamento e nos avisam para liberar créditos no seu identificador anônimo. Não vemos nem guardamos seu cartão.',
    p5: 'Não usamos cookies de rastreamento. Só localStorage para créditos, cidade preferida e preferências básicas.',
    p6: 'Você pode apagar os dados deste navegador a qualquer momento. Créditos no servidor ficam ligados ao identificador anônimo; se apagar o navegador, não há como recuperar sem conta (e não pedimos conta).',
    deleteConfirm: 'Apagar créditos e preferências deste navegador?',
    deleteButton: 'Apagar meus dados deste navegador',
  },
};
